# Linear Algebra: Summary

Linear Algebra is a branch of mathematics that deals with vectors, matrices, and linear transformations. It provides a fundamental framework for solving systems of equations, understanding geometric transformations, and analyzing data structures in computing.

In quantum computing, linear algebra is essential because quantum states, operations, and measurements are represented using vectors and matrices in a vector space known as a Hilbert space.

Here, we provide a short list of key topics and concepts in linear algebra that are essential for understanding introductory tutorials on quantum computing. The material presented here is not intended to serve as a self-contained resource for learning linear algebra. Developing a solid understanding of linear algebra requires additional study and is best supported by well-structured courses and learning materials.

## Core Concepts

### Theory

#### Vectors

A vector is an ordered collection of numbers, usually written as a column matrix:

$
\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}
$

Vectors can represent many things, such as:
    
- Geometric objects (e.g., points in space, directions)
- Data representations (e.g., RGB colors, feature vectors in machine learning)
- Quantum states (e.g., probabilistic and superposition states)

Examples: 

- A 2D vector in space:
$
\mathbf{v} = \begin{bmatrix} 3 \\ 4 \end{bmatrix}
$
    
- A probabilistic state vector in quantum computing:
$
\begin{bmatrix} 0.75 \\ 0.25 \end{bmatrix}
$

(This represents a system where the first state has a 75% probability, and the second state has a 25% probability.)

#### Matrices

A matrix is a rectangular array of numbers arranged in rows and columns:

$
A = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix}
$

Matrices are used to represent:

- Linear transformations (e.g., rotations, scaling, reflections)
- Systems of equations
- Quantum gates (in quantum computing)

For example, the identity matrix, which leaves any vector unchanged, is:

$
I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
$

#### Linear Transformations

A linear transformation is a function that preserves vector addition and scalar multiplication. It can be represented using a matrix multiplication:

$
A \mathbf{v} = \mathbf{v'}
$

where $A$ is a transformation matrix, $\mathbf{v}$ is the original vector, and $\mathbf{v'}$ is the transformed vector.

Example:
If we apply the matrix:

$
A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}
$

to the vector:

$
\mathbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix}
$

we get:

$
A \mathbf{v} = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix} \begin{bmatrix} 1 \\ 2 \end{bmatrix} = \begin{bmatrix} 2 \\ 6 \end{bmatrix}
$

This transformation scales the vector by 2 in the x-direction and 3 in the y-direction.

#### Inner Product (Dot Product)

The inner product (also known as the dot product) measures similarity between two vectors:

$
\mathbf{a} \cdot \mathbf{b} = a_1 b_1 + a_2 b_2 + \dots + a_n b_n
$

For example, if:

$
\mathbf{a} = \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \quad \mathbf{b} = \begin{bmatrix} 3 \\ 4 \end{bmatrix}
$

then:

$
\mathbf{a} \cdot \mathbf{b} = (1 \times 3) + (2 \times 4) = 3 + 8 = 11
$

This concept is crucial in quantum mechanics, where it is used to compute probabilities of measurement outcomes.

#### Tensor Product

The tensor product (denoted as $\otimes$) is a mathematical operation that combines two or more vectors, matrices, or spaces into a higher-dimensional space. In linear algebra, it is used to construct larger vector spaces from smaller ones, and in quantum computing, it is essential for describing multi-qubit systems.

Given two vectors $\mathbf{a}$ and $\mathbf{b}$, their tensor product $\mathbf{a} \otimes \mathbf{b}$ produces a new vector with a higher dimension.

For example, consider two 2D vectors:

$
\mathbf{a} = \begin{bmatrix} a_1 \\ a_2 \end{bmatrix}, \quad
\mathbf{b} = \begin{bmatrix} b_1 \\ b_2 \end{bmatrix}
$

Their tensor product is:

$
\mathbf{a} \otimes \mathbf{b} = \
\begin{bmatrix} a_1 \\ a_2 \end{bmatrix} \
\otimes \
\begin{bmatrix} b_1 \\ b_2 \end{bmatrix} \
= \
\begin{bmatrix} a_1 b_1 \\ a_1 b_2 \\ a_2 b_1 \\ a_2 b_2 \end{bmatrix} \
$

This operation creates a larger vector space that represents all possible pairwise combinations of the elements from $\mathbf{a}$ and $\mathbf{b}$.

Example

Let’s compute the tensor product of the vectors:

$
\begin{bmatrix} 1 \\ 2 \end{bmatrix} \otimes \begin{bmatrix} 3 \\ 4 \end{bmatrix}
$


$
\begin{bmatrix} 1 \times 3 \\ 1 \times 4 \\ 2 \times 3 \\ 2 \times 4 \end{bmatrix} \
= \
\begin{bmatrix} 3 \\ 4 \\ 6 \\ 8 \end{bmatrix} \
$

So, the result is a 4-dimensional vector.

#### Conjugate Transpose

Conjugate transpose (written $A^\dagger$) performs two steps on a matrix:

- *Transpose*: flip it, so rows become columns.
- *Conjugate*: flip the sign of the imaginary part of every entry (e.g. $3 + 2i$ becomes $3 - 2i$).

*Quick example:*

$$A = \begin{bmatrix} 1 & 2i \\ 3+i & 4 \end{bmatrix} \quad\Rightarrow\quad A^\dagger = \begin{bmatrix} 1 & 3-i \\ -2i & 4 \end{bmatrix}$$

*Note:* If the matrix has only real numbers, the conjugate step does nothing. It becomes just the ordinary transpose.


#### Norm of a vector

Norm of a vector measures the vector's *length* (or magnitude).

- For a vector $\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}$, the norm is $\|\mathbf{v}\| = \sqrt{|v_1|^2 + |v_2|^2 + \cdots + |v_n|^2}$.
- Geometrically, this is just the Pythagorean theorem extended to $n$ dimensions.

Example:

Take $\mathbf{v} = \begin{bmatrix} 3 \\ 4 \end{bmatrix}$:

$$\|\mathbf{v}\| = \sqrt{3^2 + 4^2} = \sqrt{9 + 16} = \sqrt{25} = 5$$

So this vector has length 5.

Since a qubit is a vector, here is an example of the norm of a qubit.

A qubit is $|\psi\rangle = \alpha|0\rangle + \beta|1\rangle$, written as a vector $\begin{bmatrix} \alpha \\ \beta \end{bmatrix}$. Its norm follows the same formula (using $|\cdot|^2$ since amplitudes can be complex):

$$\||\psi\rangle\| = \sqrt{|\alpha|^2 + |\beta|^2}$$

Take $|\psi\rangle = \tfrac{1}{\sqrt{2}}|0\rangle + \tfrac{1}{\sqrt{2}}|1\rangle$:

$$\||\psi\rangle\| = \sqrt{\left|\tfrac{1}{\sqrt2}\right|^2 + \left|\tfrac{1}{\sqrt2}\right|^2} = \sqrt{\tfrac{1}{2} + \tfrac{1}{2}} = 1$$

A **valid** qubit must have norm $= 1$ (normalized), because the squared amplitudes $|\alpha|^2$ and $|\beta|^2$ are measurement probabilities, which must sum to 1.



### Coding

Python provides powerful libraries like NumPy to perform fundamental linear algebra operations efficiently. With NumPy, we can define vectors, matrices, linear transformations, inner products, and tensor products easily.

#### Examples

In [3]:
import numpy as np

def define_and_print_vectors():
    """Defines and prints vectors"""
    v1 = np.array([1, 2, 3])  # A 3D vector
    v2 = np.array([4, 5, 6])  # Another 3D vector
    print("Vector 1:", v1)
    print("Vector 2:", v2)
    print()

def define_and_print_matrices():
    """Defines and prints matrices"""
    M1 = np.array([[1, 2], [3, 4]])  # A 2x2 matrix
    M2 = np.array([[5, 6], [7, 8]])  # Another 2x2 matrix
    print("Matrix 1:\n", M1)
    print("Matrix 2:\n", M2)
    print()

def linear_transformation():
    """Applies a linear transformation to a vector"""
    A = np.array([[2, 0], [0, 3]])  # Transformation matrix (scaling)
    v = np.array([1, 2])  # Original vector
    transformed_v = A @ v  # Matrix-vector multiplication
    print("Transformation Matrix A:\n", A)
    print("Original Vector:", v)
    print("Transformed Vector:", transformed_v)
    print()

def inner_product():
    """Computes the inner product (dot product) of two vectors"""
    v1 = np.array([1, 2, 3])
    v2 = np.array([4, 5, 6])
    dot_product = np.dot(v1, v2)
    print("Vector 1:", v1)
    print("Vector 2:", v2)
    print("Inner Product (Dot Product):", dot_product)
    print()

def tensor_product():
    """Computes the tensor product of two vectors"""
    v1 = np.array([1, 2])
    v2 = np.array([3, 4])
    tensor = np.tensordot(v1, v2, axes=0)  # Tensor product
    print("Vector 1:", v1)
    print("Vector 2:", v2)
    print("Tensor Product:\n", tensor)
    print()

def transpose():
    """Transpose of a matrix: flip rows and columns"""
    M = np.array([[1, 2], [3, 4]])
    print("Matrix M:\n", M)
    print("Transpose (M.T):\n", M.T)
    print()

def conjugate_transpose():
    """Conjugate transpose (adjoint): transpose + complex conjugate"""
    M1 = np.array([[1, 0], [3, -4]])  # complex entries so the effect is visible
    print("Matrix M1:\n", M1)
    print("Transpose only (M1.T):\n", M1.T)
    print("Conjugate Transpose (M1.conj().T):\n", M1.conj().T)
    print()    

    M2 = np.array([[1, 2j], [3 + 1j, 4]])  # complex entries so the effect is visible
    print("Matrix M2:\n", M2)
    print("Transpose only (M2.T):\n", M2.T)
    print("Conjugate Transpose (M2.conj().T):\n", M2.conj().T)
    print()    

# Running all the functions
define_and_print_vectors()
define_and_print_matrices()
linear_transformation()
inner_product()
tensor_product()
transpose()
conjugate_transpose()

Vector 1: [1 2 3]
Vector 2: [4 5 6]

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]

Transformation Matrix A:
 [[2 0]
 [0 3]]
Original Vector: [1 2]
Transformed Vector: [2 6]

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Inner Product (Dot Product): 32

Vector 1: [1 2]
Vector 2: [3 4]
Tensor Product:
 [[3 4]
 [6 8]]

Matrix M:
 [[1 2]
 [3 4]]
Transpose (M.T):
 [[1 3]
 [2 4]]

Matrix M1:
 [[ 1  0]
 [ 3 -4]]
Transpose only (M1.T):
 [[ 1  3]
 [ 0 -4]]
Conjugate Transpose (M1.conj().T):
 [[ 1  3]
 [ 0 -4]]

Matrix M2:
 [[1.+0.j 0.+2.j]
 [3.+1.j 4.+0.j]]
Transpose only (M2.T):
 [[1.+0.j 3.+1.j]
 [0.+2.j 4.+0.j]]
Conjugate Transpose (M2.conj().T):
 [[1.-0.j 3.-1.j]
 [0.-2.j 4.-0.j]]



## Learning References

1. [A series of videos about basics of linear algebra with visualizations](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

